convert to typescript
MetaMask/browser-passworder pull request #6
Opened 2020-10-27 20:30 UTC by brad-decker

2020-10-27 20:51 UTC, brad-decker commented
Need to update documentation before this is fully ready to review.

2020-10-29 14:51 UTC, brad-decker commented on src/index.ts
> +  var b64encoded = btoa(String.fromCharCode.apply(null, Array.from(view)))
this might be a functional change, could I have some additional eyes to see if this correct?

2020-12-06 21:06 UTC, rekmarks requested changes
One in-line question. There's also some files in need of newlines. Maybe we can follow up with a linting PR? There are some stylistic inconsistencies in here.

2020-12-06 21:06 UTC, rekmarks commented on src/index.ts
> +  var b64encoded = btoa(String.fromCharCode.apply(null, Array.from(view)))
Did you make this change because TypeScript complains about using the `Uint8Array`? If so, I'm thinking the `Array.from` call isn't necessary, and you could cast it to `number[]` instead.

2020-12-06 21:06 UTC, rekmarks commented on package.json
> +    "testem": "^3.2.0",
What's this new-fangled testing library about?

2020-12-07 17:00 UTC, brad-decker commented on package.json
> +    "testem": "^3.2.0",
it was used without being explicitly required. the 'test' package.json script calls testem which, if not installed globally, fails.

2020-12-07 17:17 UTC, brad-decker commented on src/index.ts
> +  var b64encoded = btoa(String.fromCharCode.apply(null, Array.from(view)))
had to cast it to unknown first otherwise it complained about the typecasting because the two types are incompatible.

2020-12-07 18:46 UTC, rekmarks approved these changes
Seems legit!

2020-12-07 19:12 UTC, merged